/*
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <https://www.gnu.org/licenses/>.
 */

import { HMK_RGBEffect } from "$lib/libhmk/rgb"
import { keyboardMetadataSchema } from "./metadata"

/**
 * Mirror of `keyboards/kbhe-75he/keyboard.json` in the libhmk RGB/HID-gamepad
 * branch. The demo keyboard uses it so the lighting, gamepad, and layout paths
 * are exercised against the only board that currently advertises RGB.
 *
 * The geometry is converted from `layouts/keyboard-layout.json` in the KBHE
 * monorepo, which is the board's own KiCad-derived layout: ISO enter, the
 * quarter-unit gap under the function row and the detached arrow cluster. The
 * ISO enter keeps only its primary rectangle because neither libhmk nor this
 * renderer models the notch.
 */
export const kbhe75heMetadata = keyboardMetadataSchema.parse({
  name: "KBHE 75HE",
  vendorId: "0x9172",
  productId: "0x0004",
  usbHighSpeed: true,

  adcResolution: 12,
  numProfiles: 4,
  numLayers: 4,
  numKeys: 82,
  numAdvancedKeys: 32,
  numDynamicKeystrokeMaxBindings: 8,
  numMacroNodes: 128,
  gamepadApis: ["xinput", "hid"],

  // `keyboard.json` declares 82 WS2812 pixels on PA15/TIM2_CH1 and the portable
  // effect set from `src/rgb.c`.
  rgb: {
    numLeds: 82,
    protocolMajor: 1,
    protocolMinor: 0,
    effects: [
      HMK_RGBEffect.STATIC,
      HMK_RGBEffect.BREATHING,
      HMK_RGBEffect.RAINBOW,
      HMK_RGBEffect.RAINBOW_WAVE,
      HMK_RGBEffect.LIVE,
    ],
    // `key_to_led` in `keyboard.json`. The firmware now undoes the serpentine
    // wiring itself, so LED indices arrive in logical key order.
    keyToLed: [...Array(82).keys()],
  },

  layout: {
    keymap: [
      [
        { key: 0 },
        { key: 1, x: 0.25 },
        { key: 2 },
        { key: 3 },
        { key: 4 },
        { key: 5, x: 0.25 },
        { key: 6 },
        { key: 7 },
        { key: 8 },
        { key: 9, x: 0.25 },
        { key: 10 },
        { key: 11 },
        { key: 12 },
        { key: 13, x: 0.25 },
      ],
      [
        { key: 14, y: 0.25 },
        { key: 15 },
        { key: 16 },
        { key: 17 },
        { key: 18 },
        { key: 19 },
        { key: 20 },
        { key: 21 },
        { key: 22 },
        { key: 23 },
        { key: 24 },
        { key: 25 },
        { key: 26 },
        { key: 27, w: 2 },
        { key: 28, x: 0.25 },
      ],
      [
        { key: 29, w: 1.5 },
        { key: 30 },
        { key: 31 },
        { key: 32 },
        { key: 33 },
        { key: 34 },
        { key: 35 },
        { key: 36 },
        { key: 37 },
        { key: 38 },
        { key: 39 },
        { key: 40 },
        { key: 41 },
        { key: 42, x: 0.25, w: 1.25, h: 2 },
        { key: 43, x: 0.25 },
      ],
      [
        { key: 44, w: 1.75 },
        { key: 45 },
        { key: 46 },
        { key: 47 },
        { key: 48 },
        { key: 49 },
        { key: 50 },
        { key: 51 },
        { key: 52 },
        { key: 53 },
        { key: 54 },
        { key: 55 },
        { key: 56 },
        { key: 57, x: 1.5 },
      ],
      [
        { key: 58, w: 1.25 },
        { key: 59 },
        { key: 60 },
        { key: 61 },
        { key: 62 },
        { key: 63 },
        { key: 64 },
        { key: 65 },
        { key: 66 },
        { key: 67 },
        { key: 68 },
        { key: 69 },
        { key: 70, w: 1.75 },
      ],
      [{ key: 71, x: 14.25, y: -0.75 }],
      [
        { key: 72, y: -0.25, w: 1.25 },
        { key: 73, w: 1.25 },
        { key: 74, w: 1.25 },
        { key: 75, w: 6.25 },
        { key: 76 },
        { key: 77 },
        { key: 78 },
      ],
      [{ key: 79, x: 13.25, y: -0.75 }, { key: 80 }, { key: 81 }],
    ],
  },

  defaultKeymap: [
    [
      "KC_ESC",
      "KC_F1",
      "KC_F2",
      "KC_F3",
      "KC_F4",
      "KC_F5",
      "KC_F6",
      "KC_F7",
      "KC_F8",
      "KC_F9",
      "KC_F10",
      "KC_F11",
      "KC_F12",
      "KC_DEL",
      "KC_GRV",
      "KC_1",
      "KC_2",
      "KC_3",
      "KC_4",
      "KC_5",
      "KC_6",
      "KC_7",
      "KC_8",
      "KC_9",
      "KC_0",
      "KC_MINS",
      "KC_EQL",
      "KC_BSPC",
      "KC_HOME",
      "KC_TAB",
      "KC_Q",
      "KC_W",
      "KC_E",
      "KC_R",
      "KC_T",
      "KC_Y",
      "KC_U",
      "KC_I",
      "KC_O",
      "KC_P",
      "KC_LBRC",
      "KC_RBRC",
      "KC_ENT",
      "KC_PGUP",
      "KC_CAPS",
      "KC_A",
      "KC_S",
      "KC_D",
      "KC_F",
      "KC_G",
      "KC_H",
      "KC_J",
      "KC_K",
      "KC_L",
      "KC_SCLN",
      "KC_QUOT",
      "KC_NUHS",
      "KC_PGDN",
      "KC_LSFT",
      "KC_NUBS",
      "KC_Z",
      "KC_X",
      "KC_C",
      "KC_V",
      "KC_B",
      "KC_N",
      "KC_M",
      "KC_COMM",
      "KC_DOT",
      "KC_SLSH",
      "KC_RSFT",
      "KC_UP",
      "KC_LCTL",
      "KC_LGUI",
      "KC_LALT",
      "KC_SPC",
      "KC_RALT",
      "MO(1)",
      "KC_RCTL",
      "KC_LEFT",
      "KC_DOWN",
      "KC_RGHT",
    ],
    [
      "_______",
      "KC_MPRV",
      "KC_MPLY",
      "KC_MNXT",
      "KC_MUTE",
      "KC_VOLD",
      "KC_VOLU",
      "_______",
      "_______",
      "_______",
      "PF(0)",
      "PF(1)",
      "PF(2)",
      "PF(3)",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "KC_HOME",
      "KC_PSCR",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "KC_END",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "KC_PGUP",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "_______",
      "KC_HOME",
      "KC_PGDN",
      "KC_END",
    ],
    [...Array(82)].map(() => "_______"),
    [...Array(82)].map(() => "_______"),
  ],
})
